services:
  dosbox:
    build: .
    image: ghcr.io/sunsided/docksbox:latest
    ports:
      - "127.0.0.1:6080:80"   # browse http://localhost:6080/
    volumes:
      - ./games:/home/dosbox/dos/games
